package com.GMS.firebaseFireStore;

public enum Collection {

    COMPANY ,
    EMPLOYEES ,
    USERS ,
    CHATTING ,
    CITIZENS ,
    NATIONS ,
    NEIGHBORHOODS ,
    STATIONS ,
    ACTIONS ,
    ACTION_DETAILS ,
    CITIZEN_ACTION_DETAILS ,
    DAILY_ACTIONS,
    ADDITION_REQUESTS;

    public enum Fields
    {
        ID,NAME,TELEPHONES,
        ADDRESS ,
             DISTRICT,
             NEIGHBORHOOD,
             QUARTER ,
        USER_NAME ,
        PASSWORD ,
        SOCIAL_ACCOUNTS ,
        TYPE_OF_JOB ,
        HIRE_DATE ,

        AQEL_DETAILS ,
               PICTURE ,

        NUMBER_OF_FAMILIES ,
        LOCATION ,
              LONGITUDE ,
              LATITUDE,

        ICON ,

        AQEL_NAME ,
        REP_NAME ,
        AGENT_NAME ,
        SELLING_PRICE ,
        DELIVERED_QUANTITY ,
        ACTION_DATE ,
        NEIGHBORHOOD_DETAILS ,
               NEIGHBORHOOD_NAME ,
               NUMBER_OF_DELIVERS ,
        STATION_DETAILS ,
               PURCHASING_PRICE ,
               PURCHASING_QUANTITY ,

        PURCHASING_DATE ,
        TOTAL ,
        DELIVERED_STATE  ,
                AQEL_VERIFIED ,
                REP_VERIFIED ,
                DELIVERED ,
                RECEIVED  ,
        DELIVERING_DATE ,
        RECEIVING_DATE

        /*
        *NOTICE THIS NOTE BELOW FOR MORE INFO FOR CONTENT OF EACH DOCUMENT
        ** EACH EMPLOYEE DOCUMENT CONTAINS THESE :
        * {
        * ID , NAME , TELEPHONE[ARRAY], ADDRESS { DISTRICT ,  NEIGHBORHOOD , QUARTER}
        *  , USER_NAME  , PASSWORD ,SOCIAL_ACCOUNTS , TYPE_OF_JOB , HIRE_DATE
        * }
        *
        ** EACH NEIGHBORHOOD DOCUMENT CONTAINS THESE :
        * {
        * ID , NAME ,TELEPHONES[ARRAY] , AQEL_DETAILS { NAME , PICTURE ,USER_NAME , PASSWORD ,TELEPHONES[ARRAY] , SOCIAL_ACCOUNTS[ARRAY] , HIRE_DATE}
        * NUMBER_OF_FAMILIES ,LOCATION {LATITUDE , LONGITUDE}
        * }
        ** EACH STATIONS DOCUMENT CONTAINS THESE :
        * {
        * ID ,NAME ,ICON , TELEPHONES[ARRAY] , LOCATION{LATITUDE , LONGITUDE}
        * }
        ** EACH DAILY_ACTIONS DOCUMENT CONTAINS THESE :
        * {
        * ID ,AQEL_NAME , REP_NAME , AGENT_NAME ,SELLING_PRICE ,DELIVERED_QUANTITY ,ACTION_DATE
        *  ,NEIGHBORHOOD_DETAILS { NEIGHBORHOOD_NAME ,NUMBER_OF_DELIVERS }
        *  ,STATION_DETAILS { NAME ,PURCHASING_PRICE , PURCHASED_QUANTITY}
        * }
        ** ACH STATION_PURCHASING_DETAILS DOCUMENT CONTAINS THESE :
        *  {
        *  ID , PURCHASING_PRICE , PURCHASED_QUANTITY ,AGENT_NAME ,PURCHASING_DATE
        * }
        ** ACH CITIZEN_ACTION_DETAILS DOCUMENT CONTAINS THESE :
        *  {
        *  ID , NAME , DELIVERED_QUANTITY ,TOTAL ,
        *  DELIVERED_STATE { AQEL_VERIFIED , REP_VERIFIED , DELIVERED , RECEIVED }
        * , DELIVERING_DATE , RECEIVING_DATE
        * }
         */

    }
}
